version: "3.8"

services:
    nextjs-app:
        container_name: wedding-website
        build: .
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        restart: always
